import { BusinessSummary, BusinessDetail, QueueLiveState, LiveTicketState, WorkstationState, AnalyticsReport } from '../types';

export const MOCK_BUSINESSES: BusinessSummary[] = [
  {
    id: 'b1-city-dental',
    name: 'City Dental & Care',
    slug: 'city-dental-care',
    category: 'Clinics & Healthcare',
    description: 'Specialized dental, orthodontic, and hygiene treatments with live virtual queueing.',
    address: '742 Evergreen Terrace, Suite 101',
    phone: '+1 (555) 234-5678',
    opening_time: '09:00',
    closing_time: '18:00',
    average_service_time: 15,
    is_open: true,
    distance_km: 0.8,
    currently_serving: '#21',
    people_waiting: 8,
    estimated_wait_minutes: 32,
    created_at: new Date().toISOString(),
  },
  {
    id: 'b2-luxe-salon',
    name: 'Luxe Hair & Beauty Lounge',
    slug: 'luxe-salon',
    category: 'Salons & Spas',
    description: 'Modern styling, haircuts, coloring, and relaxing spa sessions.',
    address: '124 Fifth Avenue, Downtown',
    phone: '+1 (555) 890-1234',
    opening_time: '10:00',
    closing_time: '20:00',
    average_service_time: 25,
    is_open: true,
    distance_km: 1.5,
    currently_serving: '#14',
    people_waiting: 5,
    estimated_wait_minutes: 20,
    created_at: new Date().toISOString(),
  },
  {
    id: 'b3-apex-auto',
    name: 'Apex Auto & Bike Service Hub',
    slug: 'apex-auto-service',
    category: 'Repair & Service Centers',
    description: 'Fast diagnostics, oil change, maintenance, and periodic inspection.',
    address: '88 Industrial Parkway',
    phone: '+1 (555) 432-8765',
    opening_time: '08:30',
    closing_time: '19:00',
    average_service_time: 20,
    is_open: true,
    distance_km: 3.2,
    currently_serving: '#08',
    people_waiting: 12,
    estimated_wait_minutes: 45,
    created_at: new Date().toISOString(),
  },
  {
    id: 'b4-metro-bank',
    name: 'Metro National Bank - Main Branch',
    slug: 'metro-bank-main',
    category: 'Banking & Finance',
    description: 'Counter service, loan assistance, teller deposits, and advisory.',
    address: '500 Financial Plaza',
    phone: '+1 (555) 777-9900',
    opening_time: '09:30',
    closing_time: '16:30',
    average_service_time: 10,
    is_open: false,
    distance_km: 2.1,
    currently_serving: '#45',
    people_waiting: 0,
    estimated_wait_minutes: 0,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_BUSINESS_DETAILS: Record<string, BusinessDetail> = {
  'city-dental-care': {
    id: 'b1-city-dental',
    name: 'City Dental & Care',
    slug: 'city-dental-care',
    category: 'Clinics & Healthcare',
    description: 'Premier orthodontic, cosmetic, and general dental care clinic with digital check-in.',
    address: '742 Evergreen Terrace, Suite 101, Medical District',
    phone: '+1 (555) 234-5678',
    opening_time: '09:00',
    closing_time: '18:00',
    average_service_time: 15,
    is_open: true,
    distance_km: 0.8,
    created_at: new Date().toISOString(),
    active_queues: [
      {
        id: 'q1-dental-main',
        business_id: 'b1-city-dental',
        name: 'General Consultation & Cleaning',
        status: 'OPEN',
        average_service_time: 15,
        max_capacity: 50,
        currently_serving_ticket: '#21',
        currently_serving_started_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
        people_waiting: 8,
        estimated_wait_minutes: 32,
        created_at: new Date().toISOString(),
      },
      {
        id: 'q2-dental-urgent',
        business_id: 'b1-city-dental',
        name: 'Urgent Tooth Pain / Extraction',
        status: 'OPEN',
        average_service_time: 20,
        max_capacity: 20,
        currently_serving_ticket: '#04',
        currently_serving_started_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        people_waiting: 2,
        estimated_wait_minutes: 15,
        created_at: new Date().toISOString(),
      }
    ]
  }
};

export const MOCK_LIVE_TICKET: LiveTicketState = {
  id: 'ticket_demo_29',
  queue_id: 'q1-dental-main',
  ticket_number: 29,
  ticket_code: '#29',
  customer_name: 'Alex Johnson',
  phone: '+1 555-0199',
  service_type: 'Dental Cleaning & Checkup',
  status: 'WAITING',
  business_name: 'City Dental & Care',
  queue_name: 'General Consultation & Cleaning',
  currently_serving: '#21',
  people_ahead: 8,
  estimated_wait_minutes: 32,
  progress_percent: 62.5,
  counter_or_station: 'Counter 2 (Room B)',
  alert_state: 'NORMAL',
  joined_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
};

export const MOCK_WORKSTATION: WorkstationState = {
  queue: {
    id: 'q1-dental-main',
    business_id: 'b1-city-dental',
    name: 'General Consultation & Cleaning',
    status: 'OPEN',
    average_service_time: 15,
    max_capacity: 50,
    created_at: new Date().toISOString(),
  },
  active_ticket: {
    id: 'ticket_24',
    queue_id: 'q1-dental-main',
    ticket_number: 24,
    ticket_code: '#24',
    customer_name: 'Johnathan Doe',
    phone: '+1 555-0188',
    service_type: 'Routine Checkup',
    status: 'SERVING',
    joined_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    called_at: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
  },
  active_service_duration_seconds: 540,
  waiting_tickets: [
    {
      id: 'ticket_25',
      queue_id: 'q1-dental-main',
      ticket_number: 25,
      ticket_code: '#25',
      customer_name: 'Sarah Mitchell',
      phone: '+1 555-0144',
      service_type: 'Teeth Whitening',
      status: 'WAITING',
      joined_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    {
      id: 'ticket_26',
      queue_id: 'q1-dental-main',
      ticket_number: 26,
      ticket_code: '#26',
      customer_name: 'David Kim',
      phone: '+1 555-0155',
      service_type: 'Consultation',
      status: 'WAITING',
      joined_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
    {
      id: 'ticket_27',
      queue_id: 'q1-dental-main',
      ticket_number: 27,
      ticket_code: '#27',
      customer_name: 'Priya Sharma',
      phone: '+1 555-0166',
      service_type: 'Dental Cleaning',
      status: 'WAITING',
      joined_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      id: 'ticket_28',
      queue_id: 'q1-dental-main',
      ticket_number: 28,
      ticket_code: '#28',
      customer_name: 'Marcus Vance',
      service_type: 'Consultation',
      status: 'WAITING',
      joined_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    {
      id: 'ticket_demo_29',
      queue_id: 'q1-dental-main',
      ticket_number: 29,
      ticket_code: '#29',
      customer_name: 'Alex Johnson (You)',
      service_type: 'Dental Cleaning & Checkup',
      status: 'WAITING',
      joined_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    }
  ],
  skipped_tickets: [
    {
      id: 'ticket_23',
      queue_id: 'q1-dental-main',
      ticket_number: 23,
      ticket_code: '#23',
      customer_name: 'Emily Watson (On Hold)',
      phone: '+1 555-0133',
      service_type: 'Consultation',
      status: 'SKIPPED',
      joined_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    }
  ],
  today_stats: {
    customers_served_today: 42,
    average_wait_minutes: 16,
    active_waitlist_count: 5,
  }
};

export const MOCK_ANALYTICS: AnalyticsReport = {
  total_customers_served: 87,
  average_wait_time_minutes: 18,
  average_service_time_minutes: 12,
  peak_hour_range: '11:00 AM - 01:00 PM',
  abandonment_rate_percent: 3.4,
  hourly_traffic: [
    { hour_label: '09 AM', customers_served: 6, average_wait_min: 8 },
    { hour_label: '10 AM', customers_served: 11, average_wait_min: 14 },
    { hour_label: '11 AM', customers_served: 16, average_wait_min: 22 },
    { hour_label: '12 PM', customers_served: 18, average_wait_min: 26 },
    { hour_label: '01 PM', customers_served: 14, average_wait_min: 20 },
    { hour_label: '02 PM', customers_served: 8, average_wait_min: 12 },
    { hour_label: '03 PM', customers_served: 10, average_wait_min: 15 },
    { hour_label: '04 PM', customers_served: 4, average_wait_min: 9 },
  ],
  service_breakdown: [
    { service_name: 'General Consultation', count: 38, percentage: 43.7 },
    { service_name: 'Teeth Cleaning', count: 26, percentage: 29.9 },
    { service_name: 'Orthodontics & Braces', count: 14, percentage: 16.1 },
    { service_name: 'Emergency Extraction', count: 9, percentage: 10.3 },
  ]
};
